---

info:
  description: Training configuration repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://adminuser:admin@eureka-schatterjee.cfapps.io/eureka
  instance:
    #hostname: roster-schatterjee.cfapps.io
    hostname: ${vcap.application.application_uris[0]}
    nonSecurePort: 80
