---
spring:
  profiles: cloud
   
message: Hello Subhankar

eureka:
  client:
    serviceUrl:
      defaultZone: http://adminuser:admin@eureka-schatterjee.cfapps.io/eureka
      
eureka:
  instance:
    hostname: company-schatterjee.cfapps.io
    nonSecurePort: 80

