---
spring:
  profiles: cloud
   
message: Hello Subhankar - This is Company App

eureka:
  client:
    serviceUrl:
      defaultZone: http://adminuser:admin@eureka-schatterjee.cfapps.io/eureka
  instance:
    #hostname: company-schatterjee.cfapps.io
    hostname: ${vcap.application.company-0.0.1-rc.22.uris[0]}
    nonSecurePort: 80


